-- jawaban NO 1
-- CREATE TABLE offices (
-- 	officeCode VARCHAR(10) NOT NULL PRIMARY KEY,
-- 	city VARCHAR(50) NOT NULL,
-- 	phone VARCHAR(50) NOT NULL,
-- 	addressline1 VARCHAR(50) NOT NULL,
-- 	addressline2 VARCHAR(50),
-- 	state VARCHAR(50),
-- 	country VARCHAR(50) NOT NULL
-- );
-- 
-- jawaban NO 2
DESCRIBE offices;
-- 
-- jawaban NO 3
-- ALTER TABLE offices
-- MODIFY phone INT (20);

-- jawaban NO 4
-- ALTER TABLE offices
-- DROP addressline2;lab1